workflows:
  atm_grg_pro:
    name: ATM GRG Pro Build
    environment:
            flutter: stable
    scripts:
      - flutter pub get
      - flutter clean
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
