workflows:
  atm_grg_pro:
    name: ATM GRG Pro Build
    environment: sdk: ">=3.0.0 <4.0.0"
      flutter: stable

    scripts:
      - flutter pub get
      - flutter clean
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
